# Includes the rules for downloading from ENA using aspera
#
# @zgr2788

rule getFastqSingle:
	input:
		getTables()[0]

	output:
		getFastq("single", 1)

	params:
		asp = asperaKey

	threads: 1

	shell:
		"bash Modules/SRActions/downloadTableSingle.sh {input} {params.asp}"


rule getFastqPaired:
	input:
		getTables()[1]

	output:
		getFastq("paired", 1)

	params:
		asp = asperaKey

	threads: 1

	shell:
		"bash Modules/SRActions/downloadTablePaired.sh {input} {params.asp}"
